"""Tests for playbook generation."""

import pytest
import yaml

from sysadmin_ai.playbooks.generator import PlaybookGenerator, CommandRecord


class TestPlaybookGenerator:
    """Test playbook generation functionality."""
    
    def test_init(self) -> None:
        """Test generator initialization."""
        generator = PlaybookGenerator()
        assert generator is not None
    
    def test_generate_ansible_empty(self) -> None:
        """Test generating Ansible playbook with empty history."""
        generator = PlaybookGenerator()
        result = generator.export([], "ansible")
        
        # Should produce valid YAML
        data = yaml.safe_load(result)
        assert isinstance(data, list)
        assert len(data) == 1
        assert data[0]["name"] == "Generated by SysAdmin AI"
    
    def test_generate_ansible_with_commands(self) -> None:
        """Test generating Ansible playbook with commands."""
        generator = PlaybookGenerator()
        
        history = [
            CommandRecord(
                command="apt install nginx",
                timestamp="2024-01-01T00:00:00",
                user="test",
                success=True,
            ),
            CommandRecord(
                command="systemctl start nginx",
                timestamp="2024-01-01T00:00:01",
                user="test",
                success=True,
            ),
        ]
        
        result = generator.export(history, "ansible")
        
        # Should produce valid YAML with tasks
        data = yaml.safe_load(result)
        assert isinstance(data, list)
        assert len(data[0]["tasks"]) > 0
    
    def test_generate_shell(self) -> None:
        """Test generating shell script."""
        generator = PlaybookGenerator()
        
        history = [
            CommandRecord(
                command="echo hello",
                timestamp="2024-01-01T00:00:00",
                user="test",
                success=True,
            ),
        ]
        
        result = generator.export(history, "shell")
        
        assert "#!/bin/bash" in result
        assert "echo hello" in result
        assert "set -euo pipefail" in result
    
    def test_generate_terraform(self) -> None:
        """Test generating Terraform configuration."""
        generator = PlaybookGenerator()
        
        history = [
            CommandRecord(
                command="useradd testuser",
                timestamp="2024-01-01T00:00:00",
                user="test",
                success=True,
            ),
        ]
        
        result = generator.export(history, "terraform")
        
        assert "terraform" in result
        assert "null_resource" in result or "local_file" in result
    
    def test_apt_command_to_task(self) -> None:
        """Test converting apt command to Ansible task."""
        generator = PlaybookGenerator()
        task = generator._command_to_ansible_task("apt install nginx curl")
        
        assert task is not None
        assert "apt" in task
        assert task["apt"]["name"] == ["nginx", "curl"]
        assert task["apt"]["state"] == "present"
    
    def test_systemctl_command_to_task(self) -> None:
        """Test converting systemctl command to Ansible task."""
        generator = PlaybookGenerator()
        task = generator._command_to_ansible_task("systemctl start nginx")
        
        assert task is not None
        assert "service" in task
        assert task["service"]["name"] == "nginx"
        assert task["service"]["state"] == "started"
    
    def test_mkdir_command_to_task(self) -> None:
        """Test converting mkdir command to Ansible task."""
        generator = PlaybookGenerator()
        task = generator._command_to_ansible_task("mkdir /tmp/testdir")
        
        assert task is not None
        assert "file" in task
        assert task["file"]["path"] == "/tmp/testdir"
        assert task["file"]["state"] == "directory"
    
    def test_unknown_command_to_shell_task(self) -> None:
        """Test that unknown commands become shell tasks."""
        generator = PlaybookGenerator()
        task = generator._command_to_ansible_task("custom_command arg1 arg2")
        
        assert task is not None
        assert "shell" in task
        assert task["shell"] == "custom_command arg1 arg2"
    
    def test_failed_commands_not_included(self) -> None:
        """Test that failed commands are not included in playbooks."""
        generator = PlaybookGenerator()
        
        history = [
            CommandRecord(
                command="apt install nginx",
                timestamp="2024-01-01T00:00:00",
                user="test",
                success=True,
            ),
            CommandRecord(
                command="failed command",
                timestamp="2024-01-01T00:00:01",
                user="test",
                success=False,
            ),
        ]
        
        result = generator.export(history, "ansible")
        data = yaml.safe_load(result)
        
        # Only successful command should be included
        tasks = data[0]["tasks"]
        assert len(tasks) == 1
    
    def test_shell_script_with_failed_commands(self) -> None:
        """Test shell script includes failed commands as comments."""
        generator = PlaybookGenerator()
        
        history = [
            CommandRecord(
                command="echo hello",
                timestamp="2024-01-01T00:00:00",
                user="test",
                success=True,
            ),
            CommandRecord(
                command="bad command",
                timestamp="2024-01-01T00:00:01",
                user="test",
                success=False,
            ),
        ]
        
        result = generator.export(history, "shell")
        
        assert "echo hello" in result
        assert "# FAILED: bad command" in result
